In [226]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

# Loading the data

In [227]:
df = pd.read_csv("http://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [228]:
df.shape

(569, 33)

In [229]:
df.drop(columns=["id", "Unnamed: 32"], inplace=True)

In [230]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# Train , Test and Split

In [231]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [232]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
236,23.21,26.97,153.50,1670.0,0.09509,0.16820,0.195000,0.12370,0.1909,0.06309,...,31.01,34.51,206.00,2944.0,0.14810,0.41260,0.58200,0.25930,0.3103,0.08677
32,17.02,23.98,112.80,899.3,0.11970,0.14960,0.241700,0.12030,0.2248,0.06382,...,20.88,32.09,136.10,1344.0,0.16340,0.35590,0.55880,0.18470,0.3530,0.08482
201,17.54,19.32,115.10,951.6,0.08968,0.11980,0.103600,0.07488,0.1506,0.05491,...,20.42,25.84,139.50,1239.0,0.13810,0.34200,0.35080,0.19390,0.2928,0.07867
432,20.18,19.54,133.80,1250.0,0.11330,0.14890,0.213300,0.12590,0.1724,0.06053,...,22.03,25.07,146.00,1479.0,0.16650,0.29420,0.53080,0.21730,0.3032,0.08075
458,13.00,25.13,82.61,520.2,0.08369,0.05073,0.012060,0.01762,0.1667,0.05449,...,14.34,31.88,91.06,628.5,0.12180,0.10930,0.04462,0.05921,0.2306,0.06291
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,12.67,17.30,81.25,489.9,0.10280,0.07664,0.031930,0.02107,0.1707,0.05984,...,13.71,21.10,88.70,574.4,0.13840,0.12120,0.10200,0.05602,0.2688,0.06888
179,12.81,13.06,81.29,508.8,0.08739,0.03774,0.009193,0.01330,0.1466,0.06133,...,13.63,16.15,86.70,570.7,0.11620,0.05445,0.02758,0.03990,0.1783,0.07319
450,11.87,21.54,76.83,432.0,0.06613,0.10640,0.087770,0.02386,0.1349,0.06612,...,12.79,28.18,83.51,507.2,0.09457,0.33990,0.32180,0.08750,0.2305,0.09952
290,14.41,19.73,96.03,651.0,0.08757,0.16760,0.136200,0.06602,0.1714,0.07192,...,15.77,22.13,101.70,767.3,0.09983,0.24720,0.22200,0.10210,0.2272,0.08799
39,13.48,20.82,88.40,559.2,0.10160,0.12550,0.106300,0.05439,0.1720,0.06419,...,15.53,26.02,107.30,740.4,0.16100,0.42250,0.50300,0.22580,0.2807,0.10710

In [233]:
X_test

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
260,20.31,27.06,132.90,1288.0,0.10000,0.10880,0.151900,0.093330,0.1814,0.05572,...,24.33,39.16,162.30,1844.0,0.15220,0.29450,0.37880,0.16970,0.3151,0.07999
86,14.48,21.46,94.25,648.2,0.09444,0.09947,0.120400,0.049380,0.2075,0.05636,...,16.21,29.25,108.40,808.9,0.13060,0.19760,0.33490,0.12250,0.3020,0.06846
57,14.71,21.59,95.55,656.9,0.11370,0.13650,0.129300,0.081230,0.2027,0.06758,...,17.87,30.70,115.70,985.5,0.13680,0.42900,0.35870,0.18340,0.3698,0.10940
232,11.22,33.81,70.79,386.8,0.07780,0.03574,0.004967,0.006434,0.1845,0.05828,...,12.36,41.78,78.44,470.9,0.09994,0.06885,0.02318,0.03002,0.2911,0.07307
117,14.87,16.67,98.64,682.5,0.11620,0.16490,0.169000,0.089230,0.2157,0.06768,...,18.81,27.37,127.10,1095.0,0.18780,0.44800,0.47040,0.20270,0.3585,0.10650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,11.60,24.49,74.23,417.2,0.07474,0.05688,0.019740,0.013130,0.1935,0.05878,...,12.44,31.62,81.39,476.5,0.09545,0.13610,0.07239,0.04815,0.3244,0.06745
214,14.19,23.81,92.87,610.7,0.09463,0.13060,0.111500,0.064620,0.2235,0.06433,...,16.86,34.85,115.00,811.3,0.15590,0.40590,0.37440,0.17720,0.4724,0.10260
126,13.61,24.69,87.76,572.6,0.09258,0.07862,0.052850,0.030850,0.1761,0.06130,...,16.89,35.64,113.20,848.7,0.14710,0.28840,0.37960,0.13290,0.3470,0.07900
543,13.21,28.06,84.88,538.4,0.08671,0.06877,0.029870,0.032750,0.1628,0.05781,...,14.37,37.17,92.48,629.6,0.10720,0.13810,0.10620,0.07958,0.2473,0.06443
389,19.55,23.21,128.90,1174.0,0.10100,0.13180,0.185600,0.102100,0.1989,0.05884,...,20.82,30.44,142.00,1313.0,0.12510,0.24140,0.38290,0.18250,0.2576,0.07602

In [234]:
y_train

236    M
32     M
201    M
432    M
458    B
      ..
325    B
179    B
450    B
290    B
39     M
Name: diagnosis, Length: 455, dtype: object

In [235]:
y_test

260    M
86     M
57     M
232    B
117    M
      ..
305    B
214    M
126    M
543    B
389    M
Name: diagnosis, Length: 114, dtype: object

# Scaling

In [236]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [237]:
X_train

array([[ 2.63150983,  1.93851293,  2.59366503, ...,  2.24601705,
         0.34118068,  0.14862991],
       [ 0.8405177 ,  1.20682763,  0.88090463, ...,  1.09517561,
         1.02273168,  0.04289386],
       [ 0.99097261,  0.06647529,  0.97769453, ...,  1.23710243,
         0.06185649, -0.29058138],
       ...,
       [-0.6495646 ,  0.60973327, -0.63280525, ..., -0.40431216,
        -0.9325376 ,  0.83998101],
       [ 0.08534978,  0.16680672,  0.17518001, ..., -0.17908046,
        -0.98521016,  0.21478272],
       [-0.18373305,  0.43354149, -0.14590997, ...,  1.72921828,
        -0.13127623,  1.25099602]])

In [238]:
X_test

array([[ 1.79243436,  1.9605369 ,  1.72676419, ...,  0.86377317,
         0.41779531, -0.2190062 ],
       [ 0.10560332,  0.59015641,  0.10027304, ...,  0.13562685,
         0.20870121, -0.8442045 ],
       [ 0.17215069,  0.62196881,  0.15498038, ...,  1.07512073,
         1.2908829 ,  1.37571034],
       ...,
       [-0.14611932,  1.3805723 , -0.17284281, ...,  0.29606587,
         0.92696339, -0.27268758],
       [-0.26185387,  2.20524771, -0.29404059, ..., -0.52649265,
        -0.66438638, -1.06272567],
       [ 1.57253872,  1.01840031,  1.55843393, ...,  1.06123658,
        -0.49998415, -0.43427396]])

# Label Encoding

In [239]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [240]:
y_train

array([1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [241]:
y_test

array([1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1])

Numpy Arrays To Pytorch Tensors

In [242]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [243]:
X_train_tensor

tensor([[ 2.6315,  1.9385,  2.5937,  ...,  2.2460,  0.3412,  0.1486],
        [ 0.8405,  1.2068,  0.8809,  ...,  1.0952,  1.0227,  0.0429],
        [ 0.9910,  0.0665,  0.9777,  ...,  1.2371,  0.0619, -0.2906],
        ...,
        [-0.6496,  0.6097, -0.6328,  ..., -0.4043, -0.9325,  0.8400],
        [ 0.0853,  0.1668,  0.1752,  ..., -0.1791, -0.9852,  0.2148],
        [-0.1837,  0.4335, -0.1459,  ...,  1.7292, -0.1313,  1.2510]],
       dtype=torch.float64)

In [244]:
X_test_tensor

tensor([[ 1.7924,  1.9605,  1.7268,  ...,  0.8638,  0.4178, -0.2190],
        [ 0.1056,  0.5902,  0.1003,  ...,  0.1356,  0.2087, -0.8442],
        [ 0.1722,  0.6220,  0.1550,  ...,  1.0751,  1.2909,  1.3757],
        ...,
        [-0.1461,  1.3806, -0.1728,  ...,  0.2961,  0.9270, -0.2727],
        [-0.2619,  2.2052, -0.2940,  ..., -0.5265, -0.6644, -1.0627],
        [ 1.5725,  1.0184,  1.5584,  ...,  1.0612, -0.5000, -0.4343]],
       dtype=torch.float64)

In [245]:
y_train_tensor

tensor([1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
        1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
        0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
        0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
        0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
        1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
        0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
        0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
        0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
        0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [246]:
y_test_tensor

tensor([1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
        1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
        1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1])

In [247]:
X_train_tensor.shape

torch.Size([455, 30])

In [248]:
X_test_tensor.shape

torch.Size([114, 30])

In [249]:
y_train_tensor.shape

torch.Size([455])

In [250]:
y_test_tensor.shape

torch.Size([114])

# Define The Model

In [251]:
class MySimpleNN():

  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad = True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad = True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

# Important Parameters

In [252]:
learning_rate = 0.1
epochs = 25

# Training Pipeline

In [253]:
# create model

model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)
  # print(y_pred)

  # loss calculation
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.6279737404169388
Epoch: 2, Loss: 3.503574337281884
Epoch: 3, Loss: 3.3747681119926702
Epoch: 4, Loss: 3.243343467811417
Epoch: 5, Loss: 3.1046615635027206
Epoch: 6, Loss: 2.9584918089918837
Epoch: 7, Loss: 2.8097379487476015
Epoch: 8, Loss: 2.6566679416346184
Epoch: 9, Loss: 2.4991613846649723
Epoch: 10, Loss: 2.3431971764903743
Epoch: 11, Loss: 2.1864634321101226
Epoch: 12, Loss: 2.029991557259205
Epoch: 13, Loss: 1.8755712317830002
Epoch: 14, Loss: 1.7222213148969558
Epoch: 15, Loss: 1.5758758788684237
Epoch: 16, Loss: 1.4412490388131622
Epoch: 17, Loss: 1.3199202779894421
Epoch: 18, Loss: 1.2133117062131968
Epoch: 19, Loss: 1.1224373820064188
Epoch: 20, Loss: 1.0475936349721564
Epoch: 21, Loss: 0.9880886413163228
Epoch: 22, Loss: 0.9422080554701131
Epoch: 23, Loss: 0.907520723347591
Epoch: 24, Loss: 0.8813712448894009
Epoch: 25, Loss: 0.8613360384010823

In [254]:
model.weights

tensor([[ 0.0646],
        [ 0.2845],
        [-0.3969],
        [ 0.0705],
        [ 0.1478],
        [-0.3620],
        [-0.0593],
        [ 0.2240],
        [-0.2786],
        [ 0.0591],
        [ 0.0022],
        [ 0.1468],
        [ 0.0163],
        [ 0.1125],
        [ 0.4904],
        [-0.3894],
        [-0.0926],
        [-0.2679],
        [ 0.3805],
        [ 0.1780],
        [ 0.0813],
        [ 0.3153],
        [ 0.0677],
        [ 0.2099],
        [ 0.3545],
        [ 0.0261],
        [ 0.3754],
        [-0.5006],
        [ 0.4503],
        [ 0.2302]], dtype=torch.float64, requires_grad=True)

In [255]:
model.bias

tensor([-0.1468], dtype=torch.float64, requires_grad=True)

# Evaluation

In [257]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()

print(y_pred)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.]])

In [259]:
accuracy = (y_pred == y_test_tensor).float().mean()
print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.48599568009376526