In [61]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

# Loading the data

In [62]:
df = pd.read_csv("http://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [63]:
df.shape

(569, 33)

In [64]:
df.drop(columns=["id", "Unnamed: 32"], inplace=True)

In [65]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# Train , Test and Split

In [66]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [67]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
479,16.25,19.51,109.80,815.8,0.10260,0.18930,0.223600,0.091940,0.2151,0.06578,...,17.390,23.05,122.10,939.7,0.13770,0.44620,0.58970,0.17750,0.3318,0.09136
54,15.10,22.02,97.26,712.8,0.09056,0.07081,0.052530,0.033340,0.1616,0.05684,...,18.100,31.69,117.70,1030.0,0.13890,0.20570,0.27120,0.15300,0.2675,0.07873
37,13.03,18.42,82.61,523.8,0.08983,0.03766,0.025620,0.029230,0.1467,0.05863,...,13.300,22.81,84.46,545.9,0.09701,0.04619,0.04833,0.05013,0.1987,0.06169
79,12.86,18.00,83.19,506.3,0.09934,0.09546,0.038890,0.023150,0.1718,0.05997,...,14.240,24.82,91.88,622.1,0.12890,0.21410,0.17310,0.07926,0.2779,0.07918
198,19.18,22.49,127.50,1148.0,0.08523,0.14280,0.111400,0.067720,0.1767,0.05529,...,23.360,32.06,166.40,1688.0,0.13220,0.56010,0.38650,0.17080,0.3193,0.09221
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456,11.63,29.29,74.87,415.1,0.09357,0.08574,0.071600,0.020170,0.1799,0.06166,...,13.120,38.81,86.04,527.8,0.14060,0.20310,0.29230,0.06835,0.2884,0.07220
547,10.26,16.58,65.85,320.8,0.08877,0.08066,0.043580,0.024380,0.1669,0.06714,...,10.830,22.04,71.08,357.4,0.14610,0.22460,0.17830,0.08333,0.2691,0.09479
506,12.22,20.04,79.47,453.1,0.10960,0.11520,0.081750,0.021660,0.2124,0.06894,...,13.160,24.17,85.13,515.3,0.14020,0.23150,0.35350,0.08088,0.2709,0.08839
441,17.27,25.42,112.40,928.8,0.08331,0.11090,0.120400,0.057360,0.1467,0.05407,...,20.380,35.46,132.80,1284.0,0.14360,0.41220,0.50360,0.17390,0.2500,0.07944
307,9.00,14.40,56.36,246.3,0.07005,0.03116,0.003681,0.003472,0.1788,0.06833,...,9.699,20.07,60.90,285.5,0.09861,0.05232,0.01472,0.01389,0.2991,0.07804

In [68]:
X_test

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
302,20.090,23.86,134.70,1247.0,0.10800,0.18380,0.228300,0.128000,0.2249,0.07469,...,23.68,29.43,158.80,1696.0,0.13470,0.33910,0.49320,0.19230,0.3294,0.09469
350,11.660,17.07,73.70,421.0,0.07561,0.03630,0.008306,0.011620,0.1671,0.05731,...,13.28,19.74,83.61,542.5,0.09958,0.06476,0.03046,0.04262,0.2731,0.06825
557,9.423,27.88,59.26,271.3,0.08123,0.04971,0.000000,0.000000,0.1742,0.06059,...,10.49,34.24,66.50,330.6,0.10730,0.07158,0.00000,0.00000,0.2475,0.06969
111,12.630,20.76,82.15,480.4,0.09933,0.12090,0.106500,0.060210,0.1735,0.07070,...,13.33,25.47,89.00,527.4,0.12870,0.22500,0.22160,0.11050,0.2226,0.08486
425,10.030,21.28,63.19,307.3,0.08117,0.03912,0.002470,0.005159,0.1630,0.06439,...,11.11,28.94,69.92,376.3,0.11260,0.07094,0.01235,0.02579,0.2349,0.08061
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
393,21.610,22.28,144.40,1407.0,0.11670,0.20870,0.281000,0.156200,0.2162,0.06606,...,26.23,28.74,172.00,2081.0,0.15020,0.57170,0.70530,0.24220,0.3828,0.10070
565,20.130,28.25,131.20,1261.0,0.09780,0.10340,0.144000,0.097910,0.1752,0.05533,...,23.69,38.25,155.00,1731.0,0.11660,0.19220,0.32150,0.16280,0.2572,0.06637
374,13.690,16.07,87.84,579.1,0.08302,0.06374,0.025560,0.020310,0.1872,0.05669,...,14.84,20.21,99.16,670.6,0.11050,0.20960,0.13460,0.06987,0.3323,0.07701
521,24.630,21.60,165.50,1841.0,0.10300,0.21060,0.231000,0.147100,0.1991,0.06739,...,29.92,26.93,205.70,2642.0,0.13420,0.41880,0.46580,0.24750,0.3157,0.09671
36,14.250,21.72,93.63,633.0,0.09823,0.10980,0.131900,0.055980,0.1885,0.06125,...,15.89,30.36,116.20,799.6,0.14460,0.42380,0.51860,0.14470,0.3591,0.10140

In [69]:
y_train

479    M
54     M
37     B
79     B
198    M
      ..
456    B
547    B
506    B
441    M
307    B
Name: diagnosis, Length: 455, dtype: object

In [70]:
y_test

302    M
350    B
557    B
111    B
425    B
      ..
393    M
565    M
374    B
521    M
36     M
Name: diagnosis, Length: 114, dtype: object

# Scaling

In [71]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [72]:
X_train

array([[ 0.68836579,  0.07622886,  0.82539088, ...,  0.9708046 ,
         0.65326169,  0.39236716],
       [ 0.34646301,  0.66148715,  0.28452252, ...,  0.59860325,
        -0.36979604, -0.30607127],
       [-0.268962  , -0.17792713, -0.34735319, ..., -0.96418667,
        -1.4644519 , -1.24838251],
       ...,
       [-0.50978047,  0.1998093 , -0.48278594, ..., -0.497036  ,
        -0.31569967,  0.22812629],
       [ 0.99161869,  1.4542673 ,  0.93753265, ...,  0.91611379,
        -0.64823321, -0.26680831],
       [-1.46710826, -1.11527308, -1.47955371, ..., -1.51474084,
         0.13298194, -0.34422824]])

In [73]:
X_test

array([[ 1.83002376,  1.09052112,  1.89936394, ...,  1.1956446 ,
         0.61507602,  0.57651601],
       [-0.67627226, -0.49270748, -0.7316544 , ..., -1.07827778,
        -0.28069614, -0.88561481],
       [-1.3413475 ,  2.02786706, -1.35447251, ..., -1.72575622,
        -0.68800995, -0.80598287],
       ...,
       [-0.07273953, -0.72587812, -0.12177572, ..., -0.66429873,
         0.66121704, -0.4011872 ],
       [ 3.17979648,  0.56355548,  3.22781254, ...,  2.03423703,
         0.39709949,  0.68822192],
       [ 0.09375226,  0.59153596,  0.12795537, ...,  0.47251054,
         1.08762368,  0.94757871]])

# Label Encoding

In [74]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [75]:
y_train

array([1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [76]:
y_test

array([1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 1])

Numpy Arrays To Pytorch Tensors

In [77]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [78]:
X_train_tensor

tensor([[ 0.6884,  0.0762,  0.8254,  ...,  0.9708,  0.6533,  0.3924],
        [ 0.3465,  0.6615,  0.2845,  ...,  0.5986, -0.3698, -0.3061],
        [-0.2690, -0.1779, -0.3474,  ..., -0.9642, -1.4645, -1.2484],
        ...,
        [-0.5098,  0.1998, -0.4828,  ..., -0.4970, -0.3157,  0.2281],
        [ 0.9916,  1.4543,  0.9375,  ...,  0.9161, -0.6482, -0.2668],
        [-1.4671, -1.1153, -1.4796,  ..., -1.5147,  0.1330, -0.3442]],
       dtype=torch.float64)

In [79]:
X_test_tensor

tensor([[ 1.8300,  1.0905,  1.8994,  ...,  1.1956,  0.6151,  0.5765],
        [-0.6763, -0.4927, -0.7317,  ..., -1.0783, -0.2807, -0.8856],
        [-1.3413,  2.0279, -1.3545,  ..., -1.7258, -0.6880, -0.8060],
        ...,
        [-0.0727, -0.7259, -0.1218,  ..., -0.6643,  0.6612, -0.4012],
        [ 3.1798,  0.5636,  3.2278,  ...,  2.0342,  0.3971,  0.6882],
        [ 0.0938,  0.5915,  0.1280,  ...,  0.4725,  1.0876,  0.9476]],
       dtype=torch.float64)

In [80]:
y_train_tensor

tensor([1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
        0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
        0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
        1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
        1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
        1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
        0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1,
        1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
        1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
        0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [81]:
y_test_tensor

tensor([1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
        0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
        1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1])

In [82]:
X_train_tensor.shape

torch.Size([455, 30])

In [83]:
X_test_tensor.shape

torch.Size([114, 30])

In [84]:
y_train_tensor.shape

torch.Size([455])

In [85]:
y_test_tensor.shape

torch.Size([114])

# Define The Model

In [86]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

# Important Parameters

In [87]:
learning_rate = 0.1
epochs = 25

In [88]:
#define loss function

loss_function = nn.BCELoss()

# Training Pipeline

In [89]:
X_train_tensor = X_train_tensor.float()
y_train_tensor = y_train_tensor.float()
X_test_tensor = X_test_tensor.float()
y_test_tensor = y_test_tensor.float()

# create model

model = MySimpleNN(X_train_tensor.shape[1])

# define optimaer

optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)
  # print(y_pred)

  # loss calculation
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  # clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.5177532434463501
Epoch: 2, Loss: 0.4297003746032715
Epoch: 3, Loss: 0.3756444454193115
Epoch: 4, Loss: 0.3383932113647461
Epoch: 5, Loss: 0.3108062148094177
Epoch: 6, Loss: 0.2893560826778412
Epoch: 7, Loss: 0.27207982540130615
Epoch: 8, Loss: 0.25778907537460327
Epoch: 9, Loss: 0.24571830034255981
Epoch: 10, Loss: 0.23534969985485077
Epoch: 11, Loss: 0.22631928324699402
Epoch: 12, Loss: 0.21836301684379578
Epoch: 13, Loss: 0.21128404140472412
Epoch: 14, Loss: 0.2049325406551361
Epoch: 15, Loss: 0.19919201731681824
Epoch: 16, Loss: 0.19397050142288208
Epoch: 17, Loss: 0.18919429183006287
Epoch: 18, Loss: 0.18480351567268372
Epoch: 19, Loss: 0.18074901401996613
Epoch: 20, Loss: 0.17698991298675537
Epoch: 21, Loss: 0.17349208891391754
Epoch: 22, Loss: 0.17022661864757538
Epoch: 23, Loss: 0.16716887056827545
Epoch: 24, Loss: 0.16429778933525085
Epoch: 25, Loss: 0.16159513592720032

In [90]:
model.linear.weight

Parameter containing:
tensor([[ 0.3506,  0.0870,  0.1572,  0.2612,  0.0037,  0.1824,  0.2185,  0.1515,
          0.0717, -0.0835,  0.2539, -0.0928,  0.2625,  0.2178,  0.0227, -0.1070,
         -0.1089,  0.1825, -0.0433,  0.0030,  0.0807,  0.2765,  0.1314,  0.3841,
          0.1263,  0.1327,  0.1123,  0.3706,  0.2723,  0.1932]],
       requires_grad=True)

In [91]:
model.linear.bias

Parameter containing:
tensor([-0.2325], requires_grad=True)

# Evaluation

In [92]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()

print(y_pred)

tensor([[1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.]])

In [93]:
accuracy = (y_pred == y_test_tensor).float().mean()
print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5138503909111023